Repository FluffySheep/CodeU2019-Team28, pull requests merged in 2019-02, with the labels that each got.

#1 Updating readme to test pull requests on GitHub
  README.md
Labels: feature, good first issue

#8 Updated the main page text.
  src/main/webapp/index.html
Labels: Setup

#9 Release Cut
  src/main/webapp/WEB-INF/appengine-web.xml
  src/main/webapp/index.html
Labels: Release

#12 Jphillips extra text
  src/main/webapp/index.html
Labels: Setup

#14 Modified code to allow recipient
  src/main/java/com/google/codeu/servlets/MessageServlet.java
Labels: Familiarization Project

#15 last commit for the week
  src/main/java/com/google/codeu/data/Datastore.java
Labels: Familiarization Project

#13 Adds the concept of recipients to Messaages, MessageServlets, and DataStore
  src/main/java/com/google/codeu/data/Datastore.java
  src/main/java/com/google/codeu/data/Message.java
  src/main/java/com/google/codeu/servlets/MessageServlet.java
Labels: Familiarization Project

#25 Fixed message constructor to take a recipient.
  src/main/java/com/google/codeu/data/Message.java
  src/main/java/com/google/codeu/servlets/LoginServlet.java
  src/main/java/com/google/codeu/servlets/LoginStatusServlet.java
  src/main/java/com/google/codeu/servlets/LogoutServlet.java
Labels: Familiarization Project, bug

#26 Expanded the server logic in About me to open a blank page with a filler email address when you navigate to https://sp19-codeu-28-4865.appspot.com/about?user=Ada@codeustudents.com
  src/main/java/com/google/codeu/servlets/AboutMeServlet.java
Labels: Familiarization Project

#27 Added html and js to display an 'about me' description on the user page along withthe ability to edit the description
  src/main/webapp/js/user-page-loader.js
  src/main/webapp/user-page.html
Labels: Familiarization Project

#17 Created Message Feed Servlet
  README.md
  src/main/java/com/google/codeu/data/Datastore.java
  src/main/java/com/google/codeu/servlets/MessageFeedServlet.java
Labels: Familiarization Project
