Repository FluffySheep/CodeU2019-Team28, pull requests merged in 2019-03, with the labels that each got.

#37 Created a User class to keep track of user information, updated the Datastore class to retrieve the date from User, updated AboutMeServlet to call the new functions in Datastore and to include a sanitizer for user inputs
  src/main/java/com/google/codeu/data/Datastore.java
  src/main/java/com/google/codeu/data/User.java
  src/main/java/com/google/codeu/servlets/AboutMeServlet.java
Labels: Familiarization Project

#34 Changed showMessageFormIfViewingSelf() function so user can see the message form as long as they're logged in even if it isn't viewing self
  src/main/webapp/js/user-page-loader.js
Labels: Familiarization Project

#35 Change getMessages function recipient variable to user.
  src/main/java/com/google/codeu/data/Datastore.java
Labels: Familiarization Project

#40 Added recipient to the list of Datastore indexes for Message which allows servlets to query Datastore by the recipient key.
  src/main/webapp/WEB-INF/index.yaml
Labels: Familiarization Project, bug

#53 setup skeleton of maps project
  src/main/webapp/Maps/maps1.html
Labels: Guided Project

#43 Adds a link to the feed and stats page in the home navigation bar.
  src/main/webapp/index.html
Labels: New Feature

#56 Information Window for Red Markers
  src/main/webapp/Maps/maps1.html
Labels: Guided Project

#55 PR #55: Clean messages for safe html usage. Added text editor to the AboutMe and Message pages.
  src/main/java/com/google/codeu/data/Datastore.java
  src/main/java/com/google/codeu/servlets/AboutMeServlet.java
  src/main/java/com/google/codeu/servlets/MessageServlet.java
  src/main/webapp/user-page.html
Labels: Guided Project

#57 Personalized Text Editor, allow links to be pasted
  src/main/java/com/google/codeu/servlets/AboutMeServlet.java
  src/main/java/com/google/codeu/servlets/MessageServlet.java
  src/main/webapp/user-page.html
Labels: Guided Project

#59 data for starbucks locations and function to parse through
  src/main/java/com/google/codeu/servlets/MapsServlet.java
  src/main/webapp/Maps/sblocations.html
  src/main/webapp/WEB-INF/starbucks-data.csv
Labels: Guided Project

#64 formatted user page with basic html
  src/main/java/com/google/codeu/servlets/MapsServlet.java
  src/main/webapp/user-page.html
Labels: Guided Project

#65 added a new user map
  src/main/webapp/Maps/user-map.html
Labels: Guided Project

#67 PR #67: Modified info windows behaviour for maps.
  src/main/webapp/Maps/user-map.html
Labels: Guided Project
