Repository FluffySheep/CodeU2019-Team28, pull requests merged in 2019-04, with the labels that each got.

#74 PR #74: Feb 10, 2019: Release Cut
  .eslintrc
  .gitignore
  .stickler.yml
  checkstyle.xml
  src/main/webapp/WEB-INF/appengine-web.xml
  src/main/webapp/index.html
Labels: Release

#93 Formatted Home Page to look similar to the mock up
  src/main/webapp/images/logo.jpg
  src/main/webapp/index.html
Labels: Open Project

#63 PR: #63: Images Part 1
  src/main/java/com/google/codeu/servlets/MessageServlet.java
  src/main/webapp/css/user-page.css
Labels: Guided Project

#104 PR #104: Geocoding first steps
  src/main/java/com/google/codeu/data/UserMarker.java
  src/main/webapp/Maps/geocode-map.html
Labels: New Feature, Open Project

#105 PR #105: User location marker
  src/main/webapp/Maps/geocode-map.html
Labels: New Feature, Open Project

#108 PR #108 : Ran java formatter on entire repository.
  src/main/java/com/google/codeu/data/UserMarker.java
  src/main/java/com/google/codeu/servlets/MessageServlet.java
  src/main/java/com/google/codeu/servlets/SearchBarServlet.java
Labels: Cleanup

#109 PR #109: Adds the concept of location to User entities.
  src/main/java/com/google/codeu/data/Datastore.java
  src/main/java/com/google/codeu/data/User.java
  src/main/java/com/google/codeu/servlets/AboutMeServlet.java
Labels: New Feature, Open Project

#111 PR #111 : Adds the maps feature to the home page navigation.
  src/main/webapp/index.html
Labels: Setup

#113 PR #113: Form submit action
  src/main/java/com/google/codeu/servlets/AboutMeServlet.java
  src/main/webapp/Maps/geocode-map.html
  src/main/webapp/user-page.html
Labels: New Feature, Open Project

#106 PR #106 : Fixes feed page UI from not rendering.
  src/main/webapp/feed.html
Labels: Familiarization Project, bug

#112 PR #112: Translation Capabilities
  pom.xml
  src/main/java/com/google/codeu/data/Message.java
  src/main/java/com/google/codeu/servlets/MessageServlet.java
Labels: Guided Project

#115 PR #115: Fix all userpage submit buttons throw a focusable error.
  src/main/webapp/user-page.html
Labels: bug

#114 PR #114: Edited SearchBar Servlet and Datastore and results-page-loader.js so that when a search query is entered, the users stored in datastore are searched through, and the ones that match them are returned in a list and populate the search results page
  src/main/java/com/google/codeu/data/Datastore.java
  src/main/java/com/google/codeu/servlets/AboutMeServlet.java
  src/main/java/com/google/codeu/servlets/SearchBarServlet.java
  src/main/webapp/index.html
  src/main/webapp/search-results.html
  src/main/webapp/user-page.html
Labels: New Feature, Open Project
